// <auto-generated />
using ArcaneVault_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcaneVault_WebAPI.Migrations
{
    [DbContext(typeof(ArcaneVaultContext))]
    partial class ArcaneVaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ArcaneVault_WebAPI.Models.ArcaneVaultUser", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserName");

                    b.HasIndex("RoleId");

                    b.ToTable("ArcaneVaultUsers");
                });

            modelBuilder.Entity("ArcaneVault_WebAPI.Models.ArcaneVaultUserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("ArcaneVaultUserRoles");
                });

            modelBuilder.Entity("ArcaneVault_WebAPI.Models.CatalogItem", b =>
                {
                    b.Property<int>("CatalogItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CatalogItemId");

                    b.HasIndex("CategoryCode");

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("ArcaneVault_WebAPI.Models.Category", b =>
                {
                    b.Property<string>("CategoryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryCode");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ArcaneVault_WebAPI.Models.CollectionItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CatalogItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StartingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("UserName");

                    b.ToTable("CollectionItems");
                });

            modelBuilder.Entity("ArcaneVault_WebAPI.Models.CollectionItemCategory", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCode")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "CategoryCode");

                    b.HasIndex("CategoryCode");

                    b.ToTable("CollectionItemCategories");
                });

            modelBuilder.Entity("ArcaneVault_WebAPI.Models.ArcaneVaultUser", b =>
                {
                    b.HasOne("ArcaneVault_WebAPI.Models.ArcaneVaultUserRole", "ArcaneVaultUserRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArcaneVaultUserRole");
                });

            modelBuilder.Entity("ArcaneVault_WebAPI.Models.CatalogItem", b =>
                {
                    b.HasOne("ArcaneVault_WebAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ArcaneVault_WebAPI.Models.CollectionItem", b =>
                {
                    b.HasOne("ArcaneVault_WebAPI.Models.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId");

                    b.HasOne("ArcaneVault_WebAPI.Models.ArcaneVaultUser", "ArcaneVaultUser")
                        .WithMany()
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArcaneVaultUser");

                    b.Navigation("CatalogItem");
                });

            modelBuilder.Entity("ArcaneVault_WebAPI.Models.CollectionItemCategory", b =>
                {
                    b.HasOne("ArcaneVault_WebAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcaneVault_WebAPI.Models.CollectionItem", "CollectionItem")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CollectionItem");
                });
#pragma warning restore 612, 618
        }
    }
}
